name: Tests

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
  workflow_call:
  workflow_dispatch:

env:
  NODE_VERSION: "22"

jobs:
  changes:
    name: Identify changes
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.dedupe.outputs.should_skip }}
    permissions:
      actions: read
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Dedupe
        id: dedupe
        uses: lojoja/action-dedupe@main
        with:
          github_token: ${{ github.token }}
          paths: |
            - .github/workflows/tests.yml
            - action.yml
            - tests/*

  test-prettier-global:
    name: Test prettier (global)
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.should_skip == 'false'
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run prettier action
        uses: ./
        with:
          install: "true"
          node_version: ${{ env.NODE_VERSION }}
          working_directory: tests

  test-prettier-project:
    name: Test prettier (project)
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.should_skip == 'false'
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run prettier action
        uses: ./
        with:
          node_version: ${{ env.NODE_VERSION }}
          working_directory: tests

  result:
    name: Tests result
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test-prettier-global
      - test-prettier-project
    steps:
      - name: Tests failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
      - name: Tests passed
        run: exit 0
